version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      spring-framework:
        patterns:
          - "org.springframework:*"
      hibernate:
        patterns:
          - "org.hibernate.orm:*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
